services:
  - type: web
    name: rhythm-game-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: your_jwt_secret_key_here
